services:
  db:
    image: postgres:16.4
    ports:
      - 127.0.0.1:${DATABASE_PORT}:${DATABASE_DOCKER_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
  redis-data: